#ifndef CLIENTSERVERQT_SERVER_ENUMS_CONTENTTYPE_H_
#define CLIENTSERVERQT_SERVER_ENUMS_CONTENTTYPE_H_
namespace test{
namespace http{
enum ContentType{
    PLAIN_TEXT,
    APPLICATION_JSON,
    APPLICATION_OCTETSTREAM,
};
}//http
}//test

#endif //CLIENTSERVERQT_SERVER_ENUMS_CONTENTTYPE_H_
